# Generated by Django 4.2.23 on 2026-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_approval_status_user_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, help_text="Full address"),
        ),
        migrations.AddField(
            model_name="user",
            name="nid_number",
            field=models.CharField(
                blank=True, help_text="National ID Number", max_length=50
            ),
        ),
    ]
