# Generated by Django 4.2.23 on 2026-01-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0003_bus_current_trip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busassignment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="busassignment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="busassignment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="busassignment",
            name="shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="busassignment",
            name="shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
