# Generated by Django 4.2.27 on 2026-01-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_number", models.CharField(max_length=20, unique=True)),
                ("license_plate", models.CharField(max_length=20)),
                ("capacity", models.PositiveIntegerField(default=50)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_buses",
                        to="schedules.route",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Buses",
                "db_table": "buses",
                "ordering": ["bus_number"],
            },
        ),
        migrations.CreateModel(
            name="ETACalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculated_eta", models.DateTimeField()),
                ("scheduled_time", models.DateTimeField()),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_delayed", models.BooleanField(default=False)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etas",
                        to="buses.bus",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etas",
                        to="schedules.stop",
                    ),
                ),
            ],
            options={
                "db_table": "eta_calculations",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="BusLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_accurate", models.BooleanField(default=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="buses.bus",
                    ),
                ),
            ],
            options={
                "db_table": "bus_locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["bus", "-timestamp"],
                        name="bus_locatio_bus_id_b023d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BusAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift_start", models.TimeField()),
                ("shift_end", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="buses.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="schedules.route",
                    ),
                ),
            ],
            options={
                "db_table": "bus_assignments",
                "ordering": ["-date", "-shift_start"],
                "unique_together": {("bus", "date", "shift_start")},
            },
        ),
    ]
