# Generated by Django 4.2.23 on 2026-01-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="bus_type",
            field=models.CharField(
                choices=[("long", "Long Route Bus"), ("shuttle", "Shuttle Bus")],
                default="long",
                max_length=20,
            ),
        ),
    ]
