# Generated by Django 4.2.23 on 2026-01-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_route_is_published_route_route_type_trip_liveeta_and_more"),
        ("buses", "0002_bus_bus_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="current_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_buses",
                to="schedules.trip",
            ),
        ),
    ]
