# Generated by Django for shuttle bus support
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='is_shuttle',
            field=models.BooleanField(default=False, help_text='Is this a shuttle bus route?'),
        ),
    ]
