# Generated by Django 4.2.23 on 2025-09-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0003_busroute_is_shuttle"),
        ("buses", "0004_rename_destination_busroute_route_and_more"),
    ]

    operations = []
