# Generated by Django 4.2.23 on 2025-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0005_merge_20250911_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="busroute",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Extra notes or shuttle schedule data (JSON)",
                null=True,
            ),
        ),
    ]
