# Generated by Django 4.2.27 on 2026-01-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("service", "Service Quality"),
                            ("timing", "Timing/Punctuality"),
                            ("cleanliness", "Cleanliness"),
                            ("driver", "Driver Behavior"),
                            ("app", "App/System"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("admin_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="buses.bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="schedules.route",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("scheduled_departure", models.TimeField()),
                ("actual_departure", models.TimeField(blank=True, null=True)),
                ("scheduled_arrival", models.TimeField()),
                ("actual_arrival", models.TimeField(blank=True, null=True)),
                ("passenger_count", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_logs",
                        to="buses.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_logs",
                        to="schedules.route",
                    ),
                ),
            ],
            options={
                "db_table": "trip_logs",
                "ordering": ["-date", "-scheduled_departure"],
            },
        ),
        migrations.CreateModel(
            name="RouteAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_trips", models.PositiveIntegerField(default=0)),
                ("on_time_trips", models.PositiveIntegerField(default=0)),
                ("delayed_trips", models.PositiveIntegerField(default=0)),
                ("total_passengers", models.PositiveIntegerField(default=0)),
                (
                    "average_delay_mins",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("issues_count", models.PositiveIntegerField(default=0)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="schedules.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_analytics",
                "ordering": ["-date"],
                "unique_together": {("route", "date")},
            },
        ),
    ]
