# Generated by Django 4.2.23 on 2026-01-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_bus_bus_type"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Published routes are visible to users"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="route_type",
            field=models.CharField(
                choices=[("long", "Long Route"), ("shuttle", "Shuttle")],
                default="long",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="schedules.route",
                    ),
                ),
            ],
            options={
                "db_table": "trips",
                "ordering": ["route", "order", "departure_time"],
            },
        ),
        migrations.CreateModel(
            name="LiveETA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.TimeField()),
                ("estimated_time", models.TimeField()),
                ("delay_minutes", models.IntegerField(default=0)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_etas",
                        to="buses.bus",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_etas",
                        to="schedules.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_etas",
                        to="schedules.trip",
                    ),
                ),
            ],
            options={
                "db_table": "live_etas",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TripStopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_times",
                        to="schedules.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_times",
                        to="schedules.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_stop_times",
                "ordering": ["trip", "order"],
                "unique_together": {("trip", "stop")},
            },
        ),
    ]
