# Generated by Django 4.2.23 on 2026-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_route_destination_name_route_origin_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="custom_days",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated days: sat,sun,mon,tue,wed,thu,fri",
                max_length=50,
            ),
        ),
    ]
