# Generated by Django 4.2.23 on 2026-01-06 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buses", "0004_alter_busassignment_options_and_more"),
        ("schedules", "0004_route_custom_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="buses.bus",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="color",
            field=models.CharField(default="#ffc107", max_length=7),
        ),
    ]
