# Generated by Django 4.2.23 on 2025-07-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_number",
                    models.CharField(
                        help_text="e.g., 'Bus 1', 'B-101'", max_length=10, unique=True
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="e.g., 'City Center', 'Main Campus'", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the route",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Route",
                "verbose_name_plural": "Bus Routes",
                "ordering": ["bus_number"],
            },
        ),
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(help_text="Scheduled departure time"),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True,
                        help_text="Scheduled arrival time (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this schedule currently active?"
                    ),
                ),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Schedule"),
                            ("EXAM", "Exam Schedule"),
                            ("SPECIAL", "Special Event Schedule"),
                        ],
                        default="REGULAR",
                        help_text="Type of schedule (e.g., Regular, Exam)",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any specific notes for this schedule (e.g., 'Runs only on weekdays')",
                        null=True,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="The bus route this schedule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="buses.busroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Schedule",
                "verbose_name_plural": "Bus Schedules",
                "ordering": ["route__bus_number", "departure_time"],
                "unique_together": {("route", "departure_time", "route_type")},
            },
        ),
    ]
