# Generated by Django 4.2.23 on 2025-07-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_route_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Schedule"),
                            ("EXAM", "Exam Schedule"),
                            ("SPECIAL", "Special Event Schedule"),
                        ],
                        default="REGULAR",
                        help_text="Set the globally active schedule type (e.g., REGULAR, EXAM). Only schedules of this type will be primarily displayed.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
