# Generated by Django 4.2.23 on 2025-09-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_globalsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stopage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stopage name (e.g., 'Main Gate', 'Science Building')",
                        max_length=100,
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(help_text="Pick-up time at this stop"),
                ),
                ("drop_time", models.TimeField(help_text="Drop time at this stop")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stopages",
                        to="buses.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ["pickup_time"],
                "unique_together": {("route", "name")},
            },
        ),
    ]
