# Generated by Django 4.2.23 on 2025-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0003_stopage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busroute",
            old_name="destination",
            new_name="route",
        ),
        migrations.RemoveField(
            model_name="busroute",
            name="description",
        ),
        migrations.RemoveField(
            model_name="stopage",
            name="drop_time",
        ),
        migrations.AddField(
            model_name="busroute",
            name="ultimate_drop_time",
            field=models.TimeField(
                blank=True, help_text="Latest pick-up time among stopages", null=True
            ),
        ),
        migrations.AddField(
            model_name="busroute",
            name="ultimate_pickup_time",
            field=models.TimeField(
                blank=True, help_text="Earliest pick-up time among stopages", null=True
            ),
        ),
    ]
