# Generated by Django 4.2.23 on 2026-01-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0005_journey"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverlocation",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_updates",
                to="buses.journey",
            ),
        ),
    ]
