# Generated by Django 4.2.23 on 2026-01-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_route_is_published_route_route_type_trip_liveeta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="destination_name",
            field=models.CharField(
                blank=True, help_text="End point (e.g., Azampur)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin_name",
            field=models.CharField(
                blank=True, help_text="Starting point (e.g., Campus)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="service_days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sat-thu", "Saturday - Thursday"),
                    ("sun-thu", "Sunday - Thursday"),
                    ("mon-fri", "Monday - Friday"),
                    ("all", "All Days"),
                    ("custom", "Custom"),
                ],
                default="sat-thu",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Trip sequence number"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_type",
            field=models.CharField(
                choices=[
                    ("shuttle", "Shuttle Bus"),
                    ("metro", "Metro Bus"),
                    ("long", "Long Road Bus"),
                ],
                default="shuttle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="arrival_time",
            field=models.TimeField(
                blank=True,
                help_text="Destination arrival time (optional for last trip)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=models.TimeField(help_text="Campus/Origin departure time"),
        ),
    ]
