# Generated by Django 5.2.7 on 2026-03-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_bus_schedule_driver_alter_route_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_type',
        ),
    ]
