# Generated by Django 4.2.23 on 2026-01-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0005_journey"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("delay", "Delay Report"),
                    ("journey_start", "Journey Started"),
                    ("journey_end", "Journey Ended"),
                    ("emergency", "Emergency"),
                    ("issue", "Issue Report"),
                    ("schedule_change", "Schedule Change"),
                    ("route_update", "Route Update"),
                    ("feedback", "Feedback"),
                    ("compliance", "Compliance Notice"),
                ],
                default="announcement",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="buses.bus",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="buses.journey",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("admin", "Admin"),
                    ("driver", "Driver"),
                    ("user", "User"),
                    ("authority", "Authority"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target",
            field=models.CharField(
                choices=[
                    ("all", "All Users"),
                    ("users", "Students/Faculty/Staff"),
                    ("drivers", "All Drivers"),
                    ("route", "Specific Route"),
                    ("admin", "Admin Only"),
                    ("authority", "Authority Only"),
                    ("admin_authority", "Admin & Authority"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
