# Generated by Django 4.2.27 on 2026-01-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True, help_text="Direction in degrees", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in m/s", null=True),
                ),
                ("is_sharing", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("session_started", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.OneToOneField(
                        limit_choices_to={"role": "driver"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_location",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Location",
                "verbose_name_plural": "Driver Locations",
                "db_table": "driver_locations",
            },
        ),
        migrations.CreateModel(
            name="LocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "driver_location_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["driver", "-timestamp"],
                        name="driver_loca_driver__9e2af7_idx",
                    )
                ],
            },
        ),
    ]
